[project]
name = "spottmee-face-embeddings-worker"
version = "0.1.0"
description = ""
authors = [
    {name = "Dmytro Stoianov", email = "dmytrostoianov05@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "insightface (>=0.7.3,<0.8.0)",
    "onnxruntime (>=1.22.1,<2.0.0)",
    "faiss-cpu (>=1.11.0.post1,<2.0.0)",
    "opencv-python (>=4.12.0.88,<5.0.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false